print("**************************************************** QUIZ SUMMARY ****************************************************")
print("Thanks for playing", name)
print("Your final score is", score)
print("You got", correct, "questions correct")
print("You got", incorrect, "questions incorrect")
